### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by ta0s** [writecrow/ocr2text#10]
Running on a nested directory set with ~3000 PDFs up to 150mb in size each. 

Win 10.
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Latest version required libraries.

over 500gb free on D:\ 
5gb free on C:\
Suspect C is being used for temp?

I'm going to look into this now.. but posting in case anyone has any immediate solution.

Percent: [####------------------------------------------------------------------------------------------------] 4.4090403853278985% Traceback (most recent call last):
  File "D:\ocr2text-main\ocr2text.py", line 151, in <module>
    count = convert_recursive(source, destination, count)
  File "D:\ocr2text-main\ocr2text.py", line 116, in convert_recursive
    count = convert(source_path, output_filename, count, pdfCounter)
  File "D:\ocr2text-main\ocr2text.py", line 121, in convert
    text = extract_tesseract(sourcefile)
  File "D:\ocr2text-main\ocr2text.py", line 90, in extract_tesseract
    page_content = pytesseract.image_to_string(Image.open(page_path))
  File "C:\Python39\lib\site-packages\pytesseract\pytesseract.py", line 413, in image_to_string
    return {
  File "C:\Python39\lib\site-packages\pytesseract\pytesseract.py", line 416, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Python39\lib\site-packages\pytesseract\pytesseract.py", line 273, in run_and_get_output
    with save(image) as (temp_name, input_filename):
  File "C:\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Python39\lib\site-packages\pytesseract\pytesseract.py", line 196, in save
    image.save(input_file_name, format=image.format)
  File "C:\Python39\lib\site-packages\PIL\Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "C:\Python39\lib\site-packages\PIL\PpmImagePlugin.py", line 149, in _save
    ImageFile._save(im, fp, [("raw", (0, 0) + im.size, 0, (rawmode, 0, 1))])
  File "C:\Python39\lib\site-packages\PIL\ImageFile.py", line 527, in _save
    s = e.encode_to_file(fh, bufsize)
OSError: [Errno 28] No space left on device

**Comment by ta0s** [comment]
Updating for other users that come across this.

In my case, the PDF which the operation failed on required around 13gb of working temp space. This particular PDF was 300 pages long. I have several PDFs in excess of 1000 pages long, which will require 1000 * 47MB, or 47 GB. 

Suffice to say, be prepared with at least 50MB per page of free space on your working drive, if you're opting to use that as a working temp folder. It can be changed.

Temp folder for my Python install is: C:\Users\[user]\AppData\Local\Temp
